project:
  type: website
  output-dir: _site
  resources:
    - "includes"

website:
  title: "Notes from Ys and elsewhere"
  repo-url: "https://github.com/LoicGrobol/notes-from-ys"
  reader-mode: true
  back-to-top-navigation: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: "https://github.com/LoicGrobol/notes-from-ys"

format:
  html:
    theme: 
      - quartz
      - custom.scss
    css: styles.css
    include-in-header:
      - text: |
          <script src="/js/mathjax-ext.js"></script>

editor: visual

