project:
  type: website
  output-dir: _site

website:
  title: "Notes from Ys and elsewhere"
  repo-url: "https://github.com/LoicGrobol/notes-from-ys"
  open-graph: true
  reader-mode: true
  back-to-top-navigation: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: "https://github.com/LoicGrobol/notes-from-ys"

format:
  html:
    theme: 
      - quartz
      - custom.scss
    css: styles.css
    code-block-background: true
    highlight-style: monokai

editor: visual

